/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.FormQuanLy;

/**
 *
 * @author User
 */
public class QuanLyNhapHang extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyNhapHang
     */
    public QuanLyNhapHang() {
        initComponents();
          SanPhamForm cspbh = new SanPhamForm();
        jPanel1.add(cspbh);
       NhapHangForm nh = new NhapHangForm();      
       
        jPanel2.add(nh);

        nh.setTarget(cspbh);
        cspbh.setTarget(nh);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1330, 900));
        setMinimumSize(new java.awt.Dimension(1330, 900));
        setPreferredSize(new java.awt.Dimension(1330, 900));
        setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(176, 196, 229), 1, true));
        jPanel4.setMaximumSize(new java.awt.Dimension(1200, 50));
        jPanel4.setMinimumSize(new java.awt.Dimension(1200, 50));
        jPanel4.setPreferredSize(new java.awt.Dimension(1200, 50));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, -4));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NHẬP HÀNG");
        jLabel1.setMaximumSize(new java.awt.Dimension(300, 58));
        jLabel1.setMinimumSize(new java.awt.Dimension(300, 58));
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 58));
        jPanel4.add(jLabel1);

        add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(176, 196, 229))); // NOI18N
        jPanel1.setAlignmentX(1.0F);
        jPanel1.setMaximumSize(new java.awt.Dimension(652, 777));
        jPanel1.setMinimumSize(new java.awt.Dimension(652, 777));
        jPanel1.setPreferredSize(new java.awt.Dimension(652, 777));
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(176, 196, 229))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(652, 777));
        jPanel2.setMinimumSize(new java.awt.Dimension(652, 777));
        jPanel2.setPreferredSize(new java.awt.Dimension(652, 777));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jPanel2);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
