/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlchdt.view.ThemSua;

import com.qlchdt.model.HoaDon;
import com.qlchdt.model.PhieuNhap;
import com.qlchdt.service.HoaDonService;
import com.qlchdt.service.PhieuNhapService;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ThemSuaPhieuNhap extends javax.swing.JFrame {

    String type;
    PhieuNhapService qlpn = new PhieuNhapService();
    PhieuNhap pnSua;

    JButton btnThem = new JButton("Thêm");
    JButton btnSua = new JButton("Sửa");
    JButton btnHuy = new JButton("Hủy");

    public ThemSuaPhieuNhap(String _type, String _mapn) {
        initComponents();
        this.type = _type;

        // 2 case Thêm - Sửa
        if (this.type.equals("Thêm")) {
            this.setTitle("Thêm phiếu nhập");
            txMaPN.setText(qlpn.getNextID());
       
            LocalDate ngayNhap = java.time.LocalDate.now();
            LocalTime gioNhap = java.time.LocalTime.now();

            this.txNgayNhap.setText(String.valueOf(ngayNhap));
            this.txGioNhap.setText(String.valueOf(gioNhap));

            btnThem.setIcon(new ImageIcon(this.getClass().getResource("/com/qlchdt/assets/icons8_add_30px.png")));
            plButton.add(btnThem);

        } else {
            this.setTitle("Sửa phiếu nhập");
            for (PhieuNhap pn : qlpn.getDspn()) {
                if (pn.getMaPN().equals(_mapn)) {
                    this.pnSua = pn;
                }
            }
            if (this.pnSua == null) {
                JOptionPane.showMessageDialog(null, "Lỗi, không tìm thấy phiếu nhập");
                this.dispose();
            }

            txMaPN.setText(this.pnSua.getMaPN());
            txMaNV.setText(this.pnSua.getMaNV());
            //txMaKH.setText(this.hdSua.getMaKhachHang());
            //txMaKM.setText(this.hdSua.getMaKhuyenMai());
            txNhaCungCap.setText(this.pnSua.getMaNCC());
            txNgayNhap.setText(String.valueOf(this.pnSua.getNgayNhap()));
            txGioNhap.setText(String.valueOf(this.pnSua.getGioNhap()));
            txTongTien.setText(String.valueOf(this.pnSua.getTongTien()));

            txMaPN.setEditable(false);

            btnSua.setIcon(new ImageIcon(this.getClass().getResource("/com/qlchdt/assets/icons8_support_30px.png")));
            plButton.add(btnSua);

        }

        btnHuy.setIcon(new ImageIcon(this.getClass().getResource("/com/qlchdt/assets/icons8_cancel_30px_1.png")));
        plButton.add(btnHuy);

        // mouse listener
        btnThem.addActionListener((ae) -> {
            // btnThemMouseClicked();
        });
        btnSua.addActionListener((ae) -> {
            //  btnSuaMouseClicked();
        });
        btnHuy.addActionListener((ae) -> {
            this.dispose();
        });

        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plButton = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txMaPN = new javax.swing.JTextField();
        txNhaCungCap = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txMaNV = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txNgayNhap = new javax.swing.JTextField();
        txGioNhap = new javax.swing.JTextField();
        txTongTien = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        plButton.setBackground(new java.awt.Color(255, 255, 255));
        plButton.setPreferredSize(new java.awt.Dimension(935, 80));
        getContentPane().add(plButton, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        txMaPN.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mã phiếu nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 102, 0))); // NOI18N
        txMaPN.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel2.add(txMaPN);

        txNhaCungCap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhà cung cấp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 102, 0))); // NOI18N
        txNhaCungCap.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel2.add(txNhaCungCap);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 90));

        txMaNV.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel1.add(txMaNV);

        jButton1.setText("jButton1");
        jButton1.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton1);

        jPanel2.add(jPanel1);

        txNgayNhap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ngày nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 102, 0))); // NOI18N
        txNgayNhap.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel2.add(txNgayNhap);

        txGioNhap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giờ nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 102, 0))); // NOI18N
        txGioNhap.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel2.add(txGioNhap);

        txTongTien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tổng tiền", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 102, 0))); // NOI18N
        txTongTien.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel2.add(txTongTien);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSuaPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSuaPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSuaPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSuaPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSuaPhieuNhap("Thêm", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel plButton;
    private javax.swing.JTextField txGioNhap;
    private javax.swing.JTextField txMaNV;
    private javax.swing.JTextField txMaPN;
    private javax.swing.JTextField txNgayNhap;
    private javax.swing.JTextField txNhaCungCap;
    private javax.swing.JTextField txTongTien;
    // End of variables declaration//GEN-END:variables
}
