/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.HoaDonService;
import DTO.Model.HoaDon;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.ItemLabelAnchor;
import org.jfree.chart.labels.ItemLabelPosition;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.CategoryItemRenderer;
import org.jfree.chart.ui.TextAnchor;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Administrator
 */
public class ThongKeDoanhThu extends javax.swing.JPanel {
    private HoaDonService hoaDonServ;
    private float tongDoanhThu=0;
    private int soLuongHoaDon=0;

    public float getTongDoanhThu() {
        return tongDoanhThu;
    }

    public int getSoLuongHoaDon() {
        return soLuongHoaDon;
    }
    
    public String summary() {
        String tongKet="";
        tongKet = "Tổng Doanh Thu: " + this.getTongDoanhThu() + " (triệu).  Số Lượng Hóa Đơn: " + this.soLuongHoaDon;
        return tongKet;
    }
    
    /**
     * Creates new form ThongKeDoanhThu
     */
    public ThongKeDoanhThu() {
        hoaDonServ = new HoaDonService();
        initComponents();
        this.setDataToChart();
    }
    
    DefaultCategoryDataset createDataset() {
        List<HoaDon> list_hd = this.hoaDonServ.getDshd();
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        Map<LocalDate, List<HoaDon>> byMonth = list_hd.stream().collect(Collectors.groupingBy(hd
                -> hd.getNgayLap().withDayOfMonth(1)));

        for (Map.Entry<LocalDate, List<HoaDon>> entry : byMonth.entrySet()) {
            LocalDate key = entry.getKey();
            List<HoaDon> val = entry.getValue();
            int soLuong = 0;
            float doanhThuThang = 0;
            for (HoaDon hd : val) {
                doanhThuThang += hd.getTongTien();
                soLuong++;
            }
            this.soLuongHoaDon += soLuong;
            this.tongDoanhThu += doanhThuThang;
            dataset.addValue(doanhThuThang, "Tổng Tiền (triệu)", key.getMonth());
            dataset.addValue(soLuong, "Số Lượng Hoá Đơn", key.getMonth());
        }
        return dataset;
    }
    
    public void setDataToChart() {
        DefaultCategoryDataset dataset = this.createDataset();
        JFreeChart barChart = ChartFactory.createBarChart("Biểu đồ thống kê doanh thu năm 2020".toUpperCase(), "Thời Gian (tháng)", "Doanh Thu", dataset);
        
        CategoryItemRenderer renderer = ((CategoryPlot)barChart.getPlot()).getRenderer();
        renderer.setDefaultItemLabelGenerator(new StandardCategoryItemLabelGenerator());
        renderer.setDefaultItemLabelsVisible(true);
        ItemLabelPosition position = new ItemLabelPosition(ItemLabelAnchor.OUTSIDE12, 
                TextAnchor.BASELINE_CENTER);
        renderer.setDefaultPositiveItemLabelPosition(position); 
        ChartPanel chartPanel = new ChartPanel(barChart);
        
        //chartPanel.setPreferredSize(new Dimension(800, 600));      
        this.setLayout(new CardLayout());
        this.add(chartPanel);
        this.validate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
