/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import BUS.ChiTietHoaDonService;
import BUS.SanPhamService;
import DTO.Model.ChiTietHoaDon;
import DTO.Model.SanPham;
import java.awt.CardLayout;
import java.text.NumberFormat;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.PieSectionLabelGenerator;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author ACER
 */
public class ThongKeSanPham extends javax.swing.JPanel {
private ChiTietHoaDonService chiTietHoaDonServ;
    private SanPhamService sanPhamServ;
    private int soLuongSanPhamBan=0;
    private int soLuongSanPham=0;
    private String hangBanChayNhat;
    
    public int getSoLuongSanPhamBan() {
        return soLuongSanPhamBan;
    }

    public int getSoLuongSanPham() {
        return soLuongSanPham;
    }
    
    public String summary() {
        String tongKet="";
        tongKet = "Số Lượng Sản Phẩm Bán: " + this.getSoLuongSanPhamBan()+"/"+this.getSoLuongSanPham()+".   Hãng bán chạy nhất: "+this.hangBanChayNhat;
        return tongKet;
    }
    
    /**
     * Creates new form ThongKeSanPham
     */
    public ThongKeSanPham() {
        chiTietHoaDonServ = new ChiTietHoaDonService();
        sanPhamServ = new SanPhamService();
        initComponents();
        this.setDataToChart();
    }
    
    String convertToFullName(String str) {
        switch (str) {
            case "SS": return "samsung".toUpperCase();
            case "OP": return "oppo".toUpperCase();
            case "NO": return "nokia".toUpperCase();
            case "IP": return "iphone".toUpperCase();
        }
        return "Unknown";
    }
    
    private DefaultPieDataset createPieDataset() {
        List<ChiTietHoaDon> list_cthd = this.chiTietHoaDonServ.getDscthd();
        List<SanPham> list_sp = this.sanPhamServ.getDssp();
        DefaultPieDataset dataset = new DefaultPieDataset();
        int max=-1;
        
        Map<String, List<ChiTietHoaDon>> byHangCTHD = list_cthd.stream().collect(Collectors.groupingBy(ct
                -> ct.getMaSanPham().substring(0, 2)));

        Map<String, List<SanPham>> byHangSP = list_sp.stream().collect(Collectors.groupingBy(sp
                -> sp.getMaHSP()));
        
        for (Map.Entry<String, List<ChiTietHoaDon>> entry : byHangCTHD.entrySet()) {
            String key = entry.getKey();
            List<ChiTietHoaDon> val = entry.getValue();
            List<SanPham> danhSachSP = byHangSP.get(key);
            
            int soLuongBan = 0;
            int soLuong = 0;
            for (ChiTietHoaDon cthd : val) {
                soLuongBan += cthd.getSoLuong();
            }
            
            for (SanPham sp : danhSachSP) {
                soLuong += sp.getSoLuong();
            }
            this.soLuongSanPham += soLuong;
            this.soLuongSanPhamBan += soLuongBan;
            // Tìm hãng bán chạy nhất
            if (soLuongBan>max) {
                this.hangBanChayNhat = convertToFullName(key);
                max = soLuongBan;
            }
            dataset.setValue(convertToFullName(key), soLuongBan);
        }
        return dataset;
    }
    
    public void setDataToChart() {
        DefaultPieDataset pieData = this.createPieDataset();
        JFreeChart pieChart = ChartFactory.createPieChart3D("Cơ cấu các hãng sản phẩm bán được ưa chuộng".toUpperCase(), pieData);
        
        PiePlot plot = (PiePlot) pieChart.getPlot();
        plot.setSimpleLabels(true);
        
        PieSectionLabelGenerator gen = new StandardPieSectionLabelGenerator(
            "{0}: {1} ({2})", NumberFormat.getInstance(), NumberFormat.getPercentInstance());
        plot.setLabelGenerator(gen);
        
        ChartPanel piePanel = new ChartPanel(pieChart);
        //chartPanel.setPreferredSize(new Dimension(800, 600));
        this.setLayout(new CardLayout());
        this.add(piePanel);
        this.validate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 673, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
