/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;

/**
 *
 * @author W7x64Pro
 */
public class ThongKe extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public ThongKe() {
        initComponents();        
        this.jTabbedPane1.setTabLayoutPolicy(jTabbedPane1.SCROLL_TAB_LAYOUT);
        Component selectedComponent = this.jTabbedPane1.getSelectedComponent();
        if (selectedComponent instanceof ThongKeDoanhThu) {
            this.summaryLabel.setText(((ThongKeDoanhThu) selectedComponent).summary());
        }
        if (selectedComponent instanceof ThongKeKho) {
            this.summaryLabel.setText(((ThongKeKho) (selectedComponent)).summary());
        }
        if (selectedComponent instanceof ThongKeNhanVien) {
            this.summaryLabel.setText(((ThongKeNhanVien) selectedComponent).summary());
        }
        if (selectedComponent instanceof ThongKeSanPham) {
            this.summaryLabel.setText(((ThongKeSanPham) ( selectedComponent)).summary());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new ThongKeDoanhThu();
        jPanel2 = new ThongKeKho()
        ;
        jPanel3 = new ThongKeSanPham()
        ;
        jPanel4 = new ThongKeNhanVien();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        summaryLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 900));
        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 600));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setLayout(new java.awt.CardLayout());
        jTabbedPane1.addTab("Doanh Thu", jPanel1);

        jPanel2.setInheritsPopupMenu(true);
        jPanel2.setLayout(new java.awt.CardLayout());
        jTabbedPane1.addTab("Kho", jPanel2);

        jPanel3.setInheritsPopupMenu(true);
        jPanel3.setLayout(new java.awt.CardLayout());
        jTabbedPane1.addTab("Sản Phẩm", jPanel3);

        jPanel4.setInheritsPopupMenu(true);
        jPanel4.setLayout(new java.awt.CardLayout());
        jTabbedPane1.addTab("Nhân Viên", jPanel4);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 196, 229)));
        jPanel5.setMaximumSize(new java.awt.Dimension(1200, 50));
        jPanel5.setMinimumSize(new java.awt.Dimension(1200, 50));
        jPanel5.setPreferredSize(new java.awt.Dimension(1200, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THỐNG KÊ");
        jLabel1.setMaximumSize(new java.awt.Dimension(300, 58));
        jLabel1.setMinimumSize(new java.awt.Dimension(300, 58));
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 58));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1198, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        summaryLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        summaryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        summaryLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        summaryLabel.setPreferredSize(new java.awt.Dimension(1200, 50));
        jPanel6.add(summaryLabel);

        add(jPanel6, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        Component selectedComponent = this.jTabbedPane1.getSelectedComponent();
        if (selectedComponent instanceof ThongKeDoanhThu) {
            this.summaryLabel.setText(((ThongKeDoanhThu) selectedComponent).summary());
        }
        if (selectedComponent instanceof ThongKeKho) {
            this.summaryLabel.setText(((ThongKeKho) (selectedComponent)).summary());
        }
        if (selectedComponent instanceof ThongKeNhanVien) {
            this.summaryLabel.setText(((ThongKeNhanVien) selectedComponent).summary());
        }
        if (selectedComponent instanceof ThongKeSanPham) {
            this.summaryLabel.setText(((ThongKeSanPham) ( selectedComponent)).summary());
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel summaryLabel;
    // End of variables declaration//GEN-END:variables
}
