/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chqldt.view;

/**
 *
 * @author Administrator
 */
public class HeThong extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienHeThong
     */
    public HeThong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeThong = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeThong.setBackground(new java.awt.Color(255, 255, 255));
        HeThong.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("                      Chức năng");
        HeThong.add(jLabel20);
        jLabel20.setBounds(0, 185, 150, 20);

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("                      Danh mục");
        HeThong.add(jLabel19);
        jLabel19.setBounds(0, 145, 150, 20);

        jButton5.setBackground(new java.awt.Color(189, 214, 218));
        jButton5.setForeground(new java.awt.Color(189, 214, 218));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/login_icon.jpg"))); // NOI18N
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 214, 218), 0, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        HeThong.add(jButton5);
        jButton5.setBounds(620, 10, 50, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/logo.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        HeThong.add(jLabel11);
        jLabel11.setBounds(0, 20, 150, 40);

        jButton3.setBackground(new java.awt.Color(189, 214, 218));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/phanquyen_icon.jpg"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 214, 218), 0));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        HeThong.add(jButton3);
        jButton3.setBounds(510, 20, 40, 40);

        jButton1.setBackground(new java.awt.Color(189, 214, 218));
        jButton1.setForeground(new java.awt.Color(189, 214, 218));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/account_icon.jpg"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 214, 218), 1, true));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        HeThong.add(jButton1);
        jButton1.setBounds(180, 10, 50, 40);

        jButton4.setBackground(new java.awt.Color(189, 214, 218));
        jButton4.setForeground(new java.awt.Color(189, 214, 218));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/qlnd_icon.jpg"))); // NOI18N
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 214, 218), 0, true));
        HeThong.add(jButton4);
        jButton4.setBounds(400, 10, 50, 50);

        jButton2.setBackground(new java.awt.Color(189, 214, 218));
        jButton2.setForeground(new java.awt.Color(189, 214, 218));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/secure_icon.jpg"))); // NOI18N
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 214, 218), 1, true));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        HeThong.add(jButton2);
        jButton2.setBounds(290, 10, 30, 40);

        jButton6.setBackground(new java.awt.Color(189, 214, 218));
        jButton6.setForeground(new java.awt.Color(189, 214, 218));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/exit_icon.jpg"))); // NOI18N
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 214, 218), 0, true));
        HeThong.add(jButton6);
        jButton6.setBounds(720, 10, 50, 50);

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(246, 246, 246));
        jLabel18.setText("                      Hệ thống");
        HeThong.add(jLabel18);
        jLabel18.setBounds(0, 100, 150, 20);

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("                      Thống kê");
        HeThong.add(jLabel21);
        jLabel21.setBounds(0, 220, 150, 20);

        jButton7.setBackground(new java.awt.Color(189, 214, 218));
        jButton7.setForeground(new java.awt.Color(189, 214, 218));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/system_icon.jpg"))); // NOI18N
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 214, 218), 0, true));
        HeThong.add(jButton7);
        jButton7.setBounds(0, 90, 150, 40);

        jButton8.setBackground(new java.awt.Color(189, 214, 218));
        jButton8.setForeground(new java.awt.Color(189, 214, 218));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/list_icon.jpg"))); // NOI18N
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 214, 218), 0, true));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        HeThong.add(jButton8);
        jButton8.setBounds(0, 140, 150, 30);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/function_icon.jpg"))); // NOI18N
        jButton9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 214, 218), 0, true));
        HeThong.add(jButton9);
        jButton9.setBounds(0, 180, 150, 30);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/statistical_icon.jpg"))); // NOI18N
        jButton10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 214, 218), 0, true));
        HeThong.add(jButton10);
        jButton10.setBounds(0, 210, 150, 40);

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("                      Trợ giúp");
        HeThong.add(jLabel22);
        jLabel22.setBounds(0, 255, 150, 20);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/support_icon.jpg"))); // NOI18N
        jButton11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 214, 218), 0, true));
        HeThong.add(jButton11);
        jButton11.setBounds(0, 250, 150, 30);

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Đăng nhập");
        HeThong.add(jLabel15);
        jLabel15.setBounds(600, 60, 90, 15);

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Thoát");
        HeThong.add(jLabel17);
        jLabel17.setBounds(720, 60, 50, 15);

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Người dùng");
        HeThong.add(jLabel16);
        jLabel16.setBounds(490, 60, 70, 15);

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Phân quyền");
        HeThong.add(jLabel13);
        jLabel13.setBounds(390, 60, 70, 15);

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Đổi mật khẩu");
        HeThong.add(jLabel12);
        jLabel12.setBounds(260, 60, 80, 15);

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("người dùng");
        HeThong.add(jLabel10);
        jLabel10.setBounds(170, 60, 70, 20);

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Thông tin ");
        HeThong.add(jLabel14);
        jLabel14.setBounds(170, 50, 70, 15);

        jLabel9.setBackground(new java.awt.Color(120, 161, 178));
        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(" Giới Thiệu");
        jLabel9.setOpaque(true);
        HeThong.add(jLabel9);
        jLabel9.setBounds(150, 90, 100, 40);

        jLabel2.setBackground(new java.awt.Color(189, 214, 218));
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(177, 191, 188), 1, true));
        jLabel2.setOpaque(true);
        HeThong.add(jLabel2);
        jLabel2.setBounds(150, 0, 200, 90);

        jLabel3.setBackground(new java.awt.Color(189, 214, 218));
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(177, 191, 188), 1, true));
        jLabel3.setOpaque(true);
        HeThong.add(jLabel3);
        jLabel3.setBounds(380, 0, 200, 90);

        jLabel4.setBackground(new java.awt.Color(189, 214, 218));
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(177, 191, 188), 1, true));
        jLabel4.setOpaque(true);
        HeThong.add(jLabel4);
        jLabel4.setBounds(600, 0, 200, 90);

        jLabel5.setBackground(new java.awt.Color(189, 214, 218));
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(177, 191, 188), 1, true));
        jLabel5.setOpaque(true);
        HeThong.add(jLabel5);
        jLabel5.setBounds(0, 90, 150, 600);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PHẦN MỀM QUẢN LÝ CỬA HÀNG ĐIỆN THOẠI DI ĐỘNG");
        HeThong.add(jLabel8);
        jLabel8.setBounds(340, 550, 700, 90);

        jLabel7.setBackground(new java.awt.Color(153, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/background_giaodien.jpg"))); // NOI18N
        HeThong.add(jLabel7);
        jLabel7.setBounds(340, 90, 700, 600);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(177, 191, 188), 0, true));
        jLabel6.setOpaque(true);
        HeThong.add(jLabel6);
        jLabel6.setBounds(320, 90, 1050, 600);

        jLabel1.setBackground(new java.awt.Color(189, 214, 218));
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(177, 191, 188), 1, true));
        jLabel1.setOpaque(true);
        HeThong.add(jLabel1);
        jLabel1.setBounds(0, 0, 1210, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(HeThong, javax.swing.GroupLayout.PREFERRED_SIZE, 1210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(HeThong, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HeThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HeThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HeThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HeThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HeThong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeThong;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
