/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlchdt.view.QuanLy;

/**
 *
 * @author User
 */
public class FormBanHang extends javax.swing.JPanel {

    public FormBanHang() {
        initComponents();

        SanPhamForm cspbh = new SanPhamForm();
        jPanel1.add(cspbh);
       HoaDonBanHangForm hdbh = new HoaDonBanHangForm();      
       
        jPanel2.add(hdbh);

        hdbh.setTarget(cspbh);
        cspbh.setTarget(hdbh);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1330, 900));
        setMinimumSize(new java.awt.Dimension(1330, 900));
        setPreferredSize(new java.awt.Dimension(1330, 900));
        setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(652, 777));
        jPanel1.setMinimumSize(new java.awt.Dimension(652, 777));
        jPanel1.setPreferredSize(new java.awt.Dimension(652, 777));
        jPanel1.setLayout(new java.awt.BorderLayout());
        add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setMaximumSize(new java.awt.Dimension(652, 777));
        jPanel2.setMinimumSize(new java.awt.Dimension(652, 777));
        jPanel2.setPreferredSize(new java.awt.Dimension(652, 777));
        jPanel2.setLayout(new java.awt.BorderLayout());
        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
