/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlchdt.view;

/**
 *
 * @author Administrator
 */
public class GiaoDienAdmin extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienHeThong
     */
    public GiaoDienAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeThong = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeThong.setBackground(new java.awt.Color(255, 255, 255));
        HeThong.setForeground(new java.awt.Color(0, 0, 0));
        HeThong.setLayout(null);

        jButton5.setBackground(new java.awt.Color(189, 214, 218));
        jButton5.setForeground(new java.awt.Color(189, 214, 218));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/login_icon.jpg"))); // NOI18N
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 214, 218), 0, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        HeThong.add(jButton5);
        jButton5.setBounds(310, 10, 50, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/logo.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        HeThong.add(jLabel11);
        jLabel11.setBounds(0, 20, 160, 40);

        jButton2.setBackground(new java.awt.Color(189, 214, 218));
        jButton2.setForeground(new java.awt.Color(189, 214, 218));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/secure_icon.jpg"))); // NOI18N
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 214, 218), 1, true));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        HeThong.add(jButton2);
        jButton2.setBounds(220, 10, 30, 40);

        jButton6.setBackground(new java.awt.Color(189, 214, 218));
        jButton6.setForeground(new java.awt.Color(189, 214, 218));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/exit_icon.jpg"))); // NOI18N
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 214, 218), 0, true));
        HeThong.add(jButton6);
        jButton6.setBounds(420, 10, 50, 50);

        jButton1.setBackground(new java.awt.Color(166, 243, 243));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/icon_nhanvien.png"))); // NOI18N
        jButton1.setText("    Nhân viên");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HeThong.add(jButton1);
        jButton1.setBounds(0, 330, 160, 45);

        jButton3.setBackground(new java.awt.Color(166, 243, 243));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/icon_user.png"))); // NOI18N
        jButton3.setText("    Khách hàng");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HeThong.add(jButton3);
        jButton3.setBounds(0, 390, 160, 45);

        jButton4.setBackground(new java.awt.Color(166, 243, 243));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/icon_cungcap.png"))); // NOI18N
        jButton4.setText("    Nhà cung cấp");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HeThong.add(jButton4);
        jButton4.setBounds(0, 450, 160, 45);

        jButton12.setBackground(new java.awt.Color(166, 243, 243));
        jButton12.setForeground(new java.awt.Color(0, 0, 0));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/icon_key.png"))); // NOI18N
        jButton12.setText("    Tài khoản");
        jButton12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HeThong.add(jButton12);
        jButton12.setBounds(0, 510, 160, 45);

        jButton13.setBackground(new java.awt.Color(166, 243, 243));
        jButton13.setForeground(new java.awt.Color(0, 0, 0));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/icon_quyen.png"))); // NOI18N
        jButton13.setText("    Quyền");
        jButton13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HeThong.add(jButton13);
        jButton13.setBounds(0, 570, 160, 45);

        jButton14.setBackground(new java.awt.Color(166, 243, 243));
        jButton14.setForeground(new java.awt.Color(0, 0, 0));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/icon_thongke.png"))); // NOI18N
        jButton14.setText("    Thống kê");
        jButton14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HeThong.add(jButton14);
        jButton14.setBounds(0, 630, 160, 45);

        jButton16.setBackground(new java.awt.Color(166, 243, 243));
        jButton16.setForeground(new java.awt.Color(0, 0, 0));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/icon_dienthoai.png"))); // NOI18N
        jButton16.setText("    Sản phẩm");
        jButton16.setFocusTraversalPolicyProvider(true);
        jButton16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        HeThong.add(jButton16);
        jButton16.setBounds(0, 90, 160, 45);

        jButton18.setBackground(new java.awt.Color(166, 243, 243));
        jButton18.setForeground(new java.awt.Color(0, 0, 0));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/icon_hoadon.png"))); // NOI18N
        jButton18.setText("     Hóa đơn ");
        jButton18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HeThong.add(jButton18);
        jButton18.setBounds(0, 150, 160, 45);

        jButton19.setBackground(new java.awt.Color(166, 243, 243));
        jButton19.setForeground(new java.awt.Color(0, 0, 0));
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/icon_khmai.png"))); // NOI18N
        jButton19.setText("    Khuyến mãi");
        jButton19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HeThong.add(jButton19);
        jButton19.setBounds(0, 270, 160, 45);

        jButton20.setBackground(new java.awt.Color(166, 243, 243));
        jButton20.setForeground(new java.awt.Color(0, 0, 0));
        jButton20.setText("          Phiếu nhập");
        HeThong.add(jButton20);
        jButton20.setBounds(0, 210, 160, 45);

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Đăng xuất");
        HeThong.add(jLabel15);
        jLabel15.setBounds(290, 60, 90, 15);

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Thoát");
        HeThong.add(jLabel17);
        jLabel17.setBounds(420, 60, 50, 15);

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Đổi mật khẩu");
        HeThong.add(jLabel12);
        jLabel12.setBounds(190, 60, 90, 15);

        jLabel5.setBackground(new java.awt.Color(166, 243, 243));
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(177, 191, 188), 1, true));
        jLabel5.setOpaque(true);
        HeThong.add(jLabel5);
        jLabel5.setBounds(0, 90, 160, 600);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PHẦN MỀM QUẢN LÝ CỬA HÀNG ĐIỆN THOẠI DI ĐỘNG");
        HeThong.add(jLabel8);
        jLabel8.setBounds(340, 550, 700, 90);

        jLabel7.setBackground(new java.awt.Color(153, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/background_giaodien.jpg"))); // NOI18N
        HeThong.add(jLabel7);
        jLabel7.setBounds(340, 90, 700, 600);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(177, 191, 188), 0, true));
        jLabel6.setOpaque(true);
        HeThong.add(jLabel6);
        jLabel6.setBounds(320, 90, 1050, 600);

        jLabel1.setBackground(new java.awt.Color(166, 243, 243));
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(177, 191, 188), 1, true));
        jLabel1.setOpaque(true);
        HeThong.add(jLabel1);
        jLabel1.setBounds(0, 0, 1210, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HeThong, javax.swing.GroupLayout.PREFERRED_SIZE, 1210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeThong, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeThong;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
