/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlchdt.view;

/**
 *
 * @author User
 */
public class TestHeThong extends javax.swing.JFrame {

    /**
     * Creates new form TestHeThong
     */
    public TestHeThong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        rSPanelImage2 = new rojerusan.RSPanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ thống");
        setMinimumSize(new java.awt.Dimension(1600, 1100));

        jPanel1.setBackground(new java.awt.Color(14, 187, 219));
        jPanel1.setMaximumSize(new java.awt.Dimension(1400, 130));
        jPanel1.setMinimumSize(new java.awt.Dimension(1400, 130));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 130));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/logo_team.png"))); // NOI18N
        rSPanelImage1.setMaximumSize(new java.awt.Dimension(220, 120));
        rSPanelImage1.setMinimumSize(new java.awt.Dimension(220, 100));
        rSPanelImage1.setPreferredSize(new java.awt.Dimension(220, 120));

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel1.add(rSPanelImage1);

        jPanel9.setOpaque(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9);

        jPanel3.setMaximumSize(new java.awt.Dimension(100, 80));
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 80));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 80));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/password.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton1.setOpaque(false);
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Đổi mật khẩu");
        jPanel3.add(jLabel2);

        jPanel1.add(jPanel3);

        jPanel5.setMaximumSize(new java.awt.Dimension(100, 80));
        jPanel5.setMinimumSize(new java.awt.Dimension(100, 80));
        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 80));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/logout.png"))); // NOI18N
        jButton2.setToolTipText("");
        jButton2.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton2.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton2.setOpaque(false);
        jButton2.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel5.add(jButton2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Đăng xuất");
        jPanel5.add(jLabel3);

        jPanel6.setMaximumSize(new java.awt.Dimension(100, 80));
        jPanel6.setMinimumSize(new java.awt.Dimension(100, 80));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 80));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/password.png"))); // NOI18N
        jButton3.setToolTipText("");
        jButton3.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton3.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton3.setOpaque(false);
        jButton3.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel6.add(jButton3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Đổi mật khẩu");
        jPanel6.add(jLabel4);

        jPanel5.add(jPanel6);

        jPanel1.add(jPanel5);

        jPanel7.setMaximumSize(new java.awt.Dimension(100, 80));
        jPanel7.setMinimumSize(new java.awt.Dimension(100, 80));
        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 80));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/shutdown.png"))); // NOI18N
        jButton4.setToolTipText("");
        jButton4.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton4.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton4.setOpaque(false);
        jButton4.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel7.add(jButton4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Thoát");
        jPanel7.add(jLabel5);

        jPanel8.setMaximumSize(new java.awt.Dimension(100, 80));
        jPanel8.setMinimumSize(new java.awt.Dimension(100, 80));
        jPanel8.setPreferredSize(new java.awt.Dimension(100, 80));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/password.png"))); // NOI18N
        jButton5.setToolTipText("");
        jButton5.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton5.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton5.setOpaque(false);
        jButton5.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel8.add(jButton5);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Đổi mật khẩu");
        jPanel8.add(jLabel6);

        jPanel7.add(jPanel8);

        jPanel1.add(jPanel7);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(14, 187, 219));
        jPanel2.setMaximumSize(new java.awt.Dimension(250, 900));
        jPanel2.setMinimumSize(new java.awt.Dimension(250, 900));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 900));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 0));

        jPanel10.setBackground(new java.awt.Color(255, 102, 102));
        jPanel10.setMaximumSize(new java.awt.Dimension(250, 900));
        jPanel10.setMinimumSize(new java.awt.Dimension(250, 900));
        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(250, 900));

        jButton6.setBackground(new java.awt.Color(255, 212, 100));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/ecommerce.png"))); // NOI18N
        jButton6.setText("BÁN HÀNG");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton6.setIconTextGap(20);
        jButton6.setMargin(new java.awt.Insets(10, 20, 10, 20));
        jButton6.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton6.setMinimumSize(new java.awt.Dimension(250, 50));
        jButton6.setOpaque(false);
        jButton6.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton6);

        jButton7.setBackground(new java.awt.Color(255, 212, 100));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/logistics.png"))); // NOI18N
        jButton7.setText("NHẬP HÀNG");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton7.setIconTextGap(20);
        jButton7.setMargin(new java.awt.Insets(10, 20, 10, 20));
        jButton7.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton7.setMinimumSize(new java.awt.Dimension(250, 50));
        jButton7.setOpaque(false);
        jButton7.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton7);

        jButton8.setBackground(new java.awt.Color(255, 212, 100));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/smartphone.png"))); // NOI18N
        jButton8.setText("SẢN PHẨM");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton8.setIconTextGap(20);
        jButton8.setMargin(new java.awt.Insets(10, 20, 10, 20));
        jButton8.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton8.setMinimumSize(new java.awt.Dimension(250, 50));
        jButton8.setOpaque(false);
        jButton8.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton8);

        jButton9.setBackground(new java.awt.Color(255, 212, 100));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/icons8_multiple_smartphones_30px.png"))); // NOI18N
        jButton9.setText("HÃNG SP");
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton9.setIconTextGap(20);
        jButton9.setMargin(new java.awt.Insets(10, 20, 10, 20));
        jButton9.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton9.setMinimumSize(new java.awt.Dimension(250, 50));
        jButton9.setOpaque(false);
        jButton9.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton9);

        jButton10.setBackground(new java.awt.Color(255, 212, 100));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/bill.png"))); // NOI18N
        jButton10.setText("HÓA ĐƠN");
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton10.setIconTextGap(20);
        jButton10.setMargin(new java.awt.Insets(10, 20, 10, 20));
        jButton10.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton10.setMinimumSize(new java.awt.Dimension(250, 50));
        jButton10.setOpaque(false);
        jButton10.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton10);

        jButton11.setBackground(new java.awt.Color(255, 212, 100));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/invoice.png"))); // NOI18N
        jButton11.setText("PHIẾU NHẬP");
        jButton11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton11.setIconTextGap(20);
        jButton11.setMargin(new java.awt.Insets(10, 20, 10, 20));
        jButton11.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton11.setMinimumSize(new java.awt.Dimension(250, 50));
        jButton11.setOpaque(false);
        jButton11.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton11);

        jButton12.setBackground(new java.awt.Color(255, 212, 100));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/sale.png"))); // NOI18N
        jButton12.setText("KHUYẾN MÃI");
        jButton12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton12.setIconTextGap(20);
        jButton12.setMargin(new java.awt.Insets(10, 20, 10, 20));
        jButton12.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton12.setMinimumSize(new java.awt.Dimension(250, 50));
        jButton12.setOpaque(false);
        jButton12.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton12);

        jButton13.setBackground(new java.awt.Color(255, 212, 100));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/employee.png"))); // NOI18N
        jButton13.setText("NHÂN VIÊN");
        jButton13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton13.setIconTextGap(20);
        jButton13.setMargin(new java.awt.Insets(10, 20, 10, 20));
        jButton13.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton13.setMinimumSize(new java.awt.Dimension(250, 50));
        jButton13.setOpaque(false);
        jButton13.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton13);

        jButton14.setBackground(new java.awt.Color(255, 212, 100));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/people.png"))); // NOI18N
        jButton14.setText("KHÁCH HÀNG");
        jButton14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton14.setIconTextGap(20);
        jButton14.setMargin(new java.awt.Insets(10, 20, 10, 20));
        jButton14.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton14.setMinimumSize(new java.awt.Dimension(250, 50));
        jButton14.setOpaque(false);
        jButton14.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton14);

        jButton15.setBackground(new java.awt.Color(255, 212, 100));
        jButton15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/supplier.png"))); // NOI18N
        jButton15.setText("NHÀ CUNG CẤP");
        jButton15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton15.setIconTextGap(20);
        jButton15.setMargin(new java.awt.Insets(10, 20, 10, 20));
        jButton15.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton15.setMinimumSize(new java.awt.Dimension(250, 50));
        jButton15.setOpaque(false);
        jButton15.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton15);

        jButton16.setBackground(new java.awt.Color(255, 212, 100));
        jButton16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/password (1).png"))); // NOI18N
        jButton16.setText("TÀI KHOẢN");
        jButton16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton16.setIconTextGap(20);
        jButton16.setMargin(new java.awt.Insets(10, 20, 10, 20));
        jButton16.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton16.setMinimumSize(new java.awt.Dimension(250, 50));
        jButton16.setOpaque(false);
        jButton16.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton16);

        jButton17.setBackground(new java.awt.Color(255, 212, 100));
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/permission.png"))); // NOI18N
        jButton17.setText("QUYỀN");
        jButton17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton17.setIconTextGap(20);
        jButton17.setMargin(new java.awt.Insets(10, 20, 10, 20));
        jButton17.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton17.setMinimumSize(new java.awt.Dimension(250, 50));
        jButton17.setOpaque(false);
        jButton17.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton17);

        jButton18.setBackground(new java.awt.Color(255, 212, 100));
        jButton18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/graphic.png"))); // NOI18N
        jButton18.setText("THỐNG KÊ");
        jButton18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton18.setIconTextGap(20);
        jButton18.setMargin(new java.awt.Insets(10, 20, 10, 20));
        jButton18.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton18.setMinimumSize(new java.awt.Dimension(250, 50));
        jButton18.setOpaque(false);
        jButton18.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton18);

        jPanel2.add(jPanel10);

        jScrollPane1.setBackground(new java.awt.Color(204, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jPanel2.add(jScrollPane1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setMaximumSize(new java.awt.Dimension(1200, 900));
        jPanel4.setMinimumSize(new java.awt.Dimension(1200, 900));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setMaximumSize(new java.awt.Dimension(1200, 900));
        jPanel11.setMinimumSize(new java.awt.Dimension(1200, 900));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20));

        rSPanelImage2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/com/qlchdt/assets/background_giaodien.jpg"))); // NOI18N
        rSPanelImage2.setMaximumSize(new java.awt.Dimension(1200, 900));
        rSPanelImage2.setMinimumSize(new java.awt.Dimension(1200, 900));
        rSPanelImage2.setPreferredSize(new java.awt.Dimension(1200, 900));
        jPanel11.add(rSPanelImage2);

        jPanel4.add(jPanel11, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestHeThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestHeThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestHeThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestHeThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestHeThong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSPanelImage rSPanelImage1;
    private rojerusan.RSPanelImage rSPanelImage2;
    // End of variables declaration//GEN-END:variables
}
