/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlchdt.view.ThemSua;

import com.qlchdt.model.HoaDon;
import com.qlchdt.service.HoaDonService;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ThemSuaHoaDon extends javax.swing.JFrame {

    String type;
    HoaDonService qlhd = new HoaDonService();
    HoaDon hdSua;

    JButton btnThem = new JButton("Thêm");
    JButton btnSua = new JButton("Sửa");
    JButton btnHuy = new JButton("Hủy");

    public ThemSuaHoaDon(String _type, String _mahd) {
        initComponents();
        this.type = _type;

        // 2 case Thêm - Sửa
        if (this.type.equals("Thêm")) {
            this.setTitle("Thêm hóa đơn");
            txMaHD.setText(qlhd.getNextID());

            LocalDate ngayLap = java.time.LocalDate.now();
            LocalTime gioLap = java.time.LocalTime.now();

            this.txNgayLap.setText(String.valueOf(ngayLap));
            this.txGioLap.setText(String.valueOf(gioLap));

            btnThem.setIcon(new ImageIcon(this.getClass().getResource("/com/qlchdt/assets/icons8_add_30px.png")));
            plButton.add(btnThem);

        } else {
            this.setTitle("Sửa hóa đơn");
            for (HoaDon hd : qlhd.getDshd()) {
                if (hd.getMaHoaDon().equals(_mahd)) {
                    this.hdSua = hd;
                }
            }
            if (this.hdSua == null) {
                JOptionPane.showMessageDialog(null, "Lỗi, không tìm thấy hóa đơn");
                this.dispose();
            }

            txMaHD.setText(this.hdSua.getMaHoaDon());
            txMaNV.setText(this.hdSua.getMaNhanVien());
            txMaKH.setText(this.hdSua.getMaKhachHang());
            txMaKM.setText(this.hdSua.getMaKhuyenMai());
            txNgayLap.setText(String.valueOf(this.hdSua.getNgayLap()));
            txGioLap.setText(String.valueOf(this.hdSua.getGioLap()));
            txTongTien.setText(String.valueOf(this.hdSua.getTongTien()));

            txMaHD.setEditable(false);

            btnSua.setIcon(new ImageIcon(this.getClass().getResource("/com/qlchdt/assets/icons8_support_30px.png")));
            plButton.add(btnSua);

        }

        btnHuy.setIcon(new ImageIcon(this.getClass().getResource("/com/qlchdt/assets/icons8_cancel_30px_1.png")));
        plButton.add(btnHuy);

        // mouse listener
        btnThem.addActionListener((ae) -> {
            // btnThemMouseClicked();
        });
        btnSua.addActionListener((ae) -> {
            //  btnSuaMouseClicked();
        });
        btnHuy.addActionListener((ae) -> {
            this.dispose();
        });

        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plButton = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txMaHD = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txMaNV = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txMaKH = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txMaKM = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txNgayLap = new javax.swing.JTextField();
        txGioLap = new javax.swing.JTextField();
        txTongTien = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        plButton.setBackground(new java.awt.Color(255, 255, 255));
        plButton.setPreferredSize(new java.awt.Dimension(935, 80));
        getContentPane().add(plButton, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        txMaHD.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mã hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 102, 0))); // NOI18N
        txMaHD.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel2.add(txMaHD);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 90));

        txMaNV.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel1.add(txMaNV);

        jButton1.setText("jButton1");
        jButton1.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton1);

        jPanel2.add(jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 90));

        txMaKH.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel3.add(txMaKH);

        jButton2.setText("jButton2");
        jButton2.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel3.add(jButton2);

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Khuyến mãi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 90));

        txMaKM.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel4.add(txMaKM);

        jButton3.setText("jButton3");
        jButton3.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel4.add(jButton3);

        jPanel2.add(jPanel4);

        txNgayLap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ngày lập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 102, 0))); // NOI18N
        txNgayLap.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel2.add(txNgayLap);

        txGioLap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giờ lập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 102, 0))); // NOI18N
        txGioLap.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel2.add(txGioLap);

        txTongTien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tổng tiền", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 102, 0))); // NOI18N
        txTongTien.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel2.add(txTongTien);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSuaHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSuaHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSuaHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSuaHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSuaHoaDon("Thêm", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel plButton;
    private javax.swing.JTextField txGioLap;
    private javax.swing.JTextField txMaHD;
    private javax.swing.JTextField txMaKH;
    private javax.swing.JTextField txMaKM;
    private javax.swing.JTextField txMaNV;
    private javax.swing.JTextField txNgayLap;
    private javax.swing.JTextField txTongTien;
    // End of variables declaration//GEN-END:variables
}
